export {default as Header} from "./Header/Header"
export {default as Nav} from "./Nav/Nav"
export {default as Articles} from "./Articles/Articles"
export {default as Latest} from "./Latest/Latest"
export {default as Footer} from "./Footer/Footer"